### ISSUE TITLE
macos15.1 安装成功，但连接失败

### ISSUE THREAD

**Issue by zhangzc1209** [helson-lin/iNode_Client_Sequoia#3]
佬，我根据教程进行的二次封包，安装文件时日志有报错，但是安装完成了，连接vpn还是报错“查询 SSLVPN网关参数失败，请检查网络配置或联系管理员”，受累看下连接失败是否和安装时输出的相关报错日志有关，期待大佬回复
<img width="1307" alt="image" src="https://github.com/user-attachments/assets/dc1ddbcc-7cc5-4999-99a3-18eba886f96f" />
<img width="560" alt="image" src="https://github.com/user-attachments/assets/b94e511e-3baa-41a4-803d-49703a5f3c66" />

**Comment by helson-lin** [comment]
将原包里面的 clientFiles 文件夹内容复制到你的/Application/iNodeclinet 下面试试

**Comment by zhangzc1209** [comment]
clientFiles文件夹下有三个空的文件夹

<img width="1097" alt="image" src="https://github.com/user-attachments/assets/da1c52f4-da7b-4f2d-bbda-333f24d18a58" />

**Comment by helson-lin** [comment]
你的网关配置检查了嘛 需要和你同事的保持一致

**Comment by helson-lin** [comment]
检查一下 conf文件是否都有文件

**Comment by zhangzc1209** [comment]
<img width="646" alt="image" src="https://github.com/user-attachments/assets/18d3641c-e91e-421f-abe4-eb1bb6586a74" />
 conf文件下就这么一个文件，一样的







<img width="690" alt="image" src="https://github.com/user-attachments/assets/50ee216e-4153-421e-95cf-5ba360979db5" />

我这的CodeResources是文稿，同事是可执行文件，我把我的改成可执行文件了，还是不太行

还有哪些位置可以排查吗

**Comment by zhangzc1209** [comment]
> 你的网关配置检查完了嘛，需要和你的同事保持一致

网关配置您指的都是哪些文件

**Comment by zhangzc1209** [comment]
又换了个同事的inode，他的/clientFiles/7000文件下有配置的连接信息（.icnf文件），我复制到我的文件下，打开inode，还是不显示这些连接，在inode上保存之后，也存不到clientFiles下，是这挂载出问题了吗

**Comment by helson-lin** [comment]
你这是啥意思你记得修改权限 文件的 再试试

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月24日 09:51 |
| 收件人 | helson-lin/iNode_Client_Sequoia ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/iNode_Client_Sequoia] macos15.1 安装成功，但连接失败 (Issue #3) |

又换了个同事的inode，他的/clientFiles/7000文件下有配置的连接信息（.icnf文件），我复制到我的文件下，打开inode，还是不显示这些连接，在inode上保存之后，也存不到clientFiles下，是这挂载出问题了吗

**Comment by helson-lin** [comment]
直接复制没有权限的

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月24日 09:51 |
| 收件人 | helson-lin/iNode_Client_Sequoia ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/iNode_Client_Sequoia] macos15.1 安装成功，但连接失败 (Issue #3) |

又换了个同事的inode，他的/clientFiles/7000文件下有配置的连接信息（.icnf文件），我复制到我的文件下，打开inode，还是不显示这些连接，在inode上保存之后，也存不到clientFiles下，是这挂载出问题了吗

**Comment by helson-lin** [comment]
> 又换了个同事的inode，他的/clientFiles/7000文件下有配置的连接信息（.icnf文件），我复制到我的文件下，打开inode，还是不显示这些连接，在inode上保存之后，也存不到clientFiles下，是这挂载出问题了吗

chmod 775 clientfiles 试试

**Comment by zhangzc1209** [comment]
su -i 了，现在是这个问题，这个报错不应该吧

<img width="1480" alt="image" src="https://github.com/user-attachments/assets/feba3833-64e2-48b3-9c4e-87481e0b355d" />

**Comment by helson-lin** [comment]
你 lib文件夹替换了嘛，缺少依赖了。安装不管这个连接有问题嘛，有问题将你的原包里面的 lib文件拷贝到/usr/local/lib 下面记得授权

**Comment by zhangzc1209** [comment]
刚手动拷贝的，提示安全问题，是这个安全问题导致的preinstall无法复制到/usr/local/lib 吧


<img width="260" alt="image" src="https://github.com/user-attachments/assets/a1584bef-476d-46ee-be2f-46f93390d6a5" />

**Comment by zhangzc1209** [comment]
> 你 lib文件夹替换了嘛，缺少依赖了。安装不管这个连接有问题嘛，有问题将你的原包里面的 lib文件拷贝到/usr/local/lib 下面记得授权

自己的lib下替换了，但是拷贝到/usr/local/lib时失败了

**Comment by helson-lin** [comment]
你在系统设置里面安全和隐私信任

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月24日 11:38 |
| 收件人 | helson-lin/iNode_Client_Sequoia ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/iNode_Client_Sequoia] macos15.1 安装成功，但连接失败 (Issue #3) |

刚手动拷贝的，提示安全问题，是这个安全问题导致的preinstall无法复制到/usr/local/lib 吧

image.png (view on web)

**Comment by helson-lin** [comment]
使用命令cp拷贝 图形化不允许拷贝

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月24日 11:39 |
| 收件人 | helson-lin/iNode_Client_Sequoia ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/iNode_Client_Sequoia] macos15.1 安装成功，但连接失败 (Issue #3) |

你 lib文件夹替换了嘛，缺少依赖了。安装不管这个连接有问题嘛，有问题将你的原包里面的 lib文件拷贝到/usr/local/lib 下面记得授权

自己的lib下替换了，但是拷贝到/usr/local/lib时失败了

**Comment by helson-lin** [comment]
你把你的原包和封装后的给我看看

**Comment by zhangzc1209** [comment]
生成的包 ：https://pan.baidu.com/s/1G7e-EO8XrL13NXKcBoKDTw?pwd=a9p7 
公司给的包，同事的包：https://pan.baidu.com/s/1RA0juOOxdIQydGF2KVxsww?pwd=a9p7 
大哥受累给看下，如果方便的话，远程技术支持下也行，万分感谢



> 你把你的原包和封装后给我看看

**Comment by helson-lin** [comment]
可以从 123 网盘传一下嘛 百度网盘我手头没有会员太慢了







---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月24日 14:14 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [helson-lin/iNode_Client_Sequoia] macos15.1 安装成功，但连接失败 (Issue #3) |

生成的包 ：https://pan.baidu.com/s/1G7e-EO8XrL13NXKcBoKDTw?pwd=a9p7
公司给的包，同事的包：https://pan.baidu.com/s/1RA0juOOxdIQydGF2KVxsww?pwd=a9p7
大哥受累给看下，如果方便的话，远程技术支持下也行，万分感谢

你把你的原包和封装后给我看看

**Comment by zhangzc1209** [comment]
好的，稍等一下

**Comment by zhangzc1209** [comment]
受累看下
https://www.123865.com/s/vrteTd-aGb9A

**Comment by helson-lin** [comment]
用这个https://www.123865.com/s/WNhDVv-4HwUh

你把他的clientFiles/7000 文件夹下面的文件复制到你的安装之后的应用程序的 iNodeClinet/cliennFiles/7000 下面去再试试看，

**Comment by zhangzc1209** [comment]
大哥,您发的这个包可以用,谢谢您,帮大忙了,多谢多谢

**Comment by helson-lin** [comment]
👌 issue 关闭了


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月24日 16:24 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [helson-lin/iNode_Client_Sequoia] macos15.1 安装成功，但连接失败 (Issue #3) |

大哥,您发的这个包可以用,谢谢您,帮大忙了,多谢多谢

**Comment by zhangzc1209** [comment]
还是不知道自己哪里操作出了问题...您的build之前的文件夹能发我一下吗

**Comment by helson-lin** [comment]
https://www.123865.com/s/WNhDVv-xHwUh


Lib 文件夹替换了。 StartupItems 替换了。然后将 inodeClient 替换成你公司的包里面的。





---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月24日 16:26 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [helson-lin/iNode_Client_Sequoia] macos15.1 安装成功，但连接失败 (Issue #3) |

还是不知道自己哪里操作出了问题...您的build之前的文件夹能发我一下吗

**Comment by zhangzc1209** [comment]
StartupItems在哪，没找到这个文件啊，StartupParameters.plist这个吗，还是那些sh脚本

**Comment by helson-lin** [comment]
inode/公司的/iNodeClient.pkg/Contents/Archive.pax/Library/StartupItems

|


|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月24日 16:38 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [helson-lin/iNode_Client_Sequoia] macos15.1 安装成功，但连接失败 (Issue #3) |

StartupItems在哪，没找到这个文件啊，StartupParameters.plist这个吗，还是那些sh脚本

**Comment by zhangzc1209** [comment]
找到了，多谢大哥

**Comment by helson-lin** [comment]
不客气没其他问题，麻烦你把 issue 关了


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月24日 16:49 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [helson-lin/iNode_Client_Sequoia] macos15.1 安装成功，但连接失败 (Issue #3) |

找到了，多谢大哥

**Comment by zhangzc1209** [comment]
好的，多谢大哥
